### ISSUE TITLE
Ellipsis not rendered in latest Firefox and IE11

### ISSUE THREAD

**Issue by vitality82** [Frondor/vue-line-clamp#17]
The css "text-overflow: ellipsis" does not have any affect.

**Comment by Frondor** [comment]
Hello, I just tested in latest firefox and it works flawlessly.
![https://i.imgur.com/c5dBScc.png](https://i.imgur.com/c5dBScc.png)

For IE11 I'm pretty sure it fires the fallback method, which uses javacript so if any error happens, you should be able to provide a stack trace. Do you see any error in the console? Are you sure your own CSS styles aren't conflicting with the ellipsis?

**Comment by vitality82** [comment]
It's possible my styles combination is preventing the ellipsis. I've also tried with removing a good part of the styles and in different containers. I've tested this using browserstack and there was no error thrown to provide. This changes the eye of mordor onto CSS, which is applied by the directive. Have you verified the set of dots are displayed for IE11? Thanks!

**Comment by Frondor** [comment]
Now I think I get your point. Basically, the line-clamp strategy works but you are not seeing the three dots in IE11, right?
That's a normal behavior I'm afraid, since we don't have where in the text node, to place the dots. It's in the readme.
The lines get "clamped" but ellipsis dots won't show up in older browsers.

**Comment by vitality82** [comment]
That is correct, the line-clamp works but without the "..." I can't use it. Latest FF and IE11 are still fairly used by clients. From a UX standpoint looking at someones truncated sentence would present a bit incorrectly. I've solved my case with a custom truncation on number of chars dynamically. Thanks!

**Comment by Frondor** [comment]
I'm glad you solved your issue! 
You probably misunderstood the scope of this package, since it's called `vue-line-clamp`, what it tries to solve is just that, line clamping / text truncating, which doesn't necessarily implies adding an ellipsis character to the text boundary.
> "The line-clamp property truncates text at a specific number of lines."
> -- <cite>https://css-tricks.com/almanac/properties/l/line-clamp</cite>

And the reason why I don't include a fix for that is simply because I'd like to keep the "lightweight" part of this package's description :)
Such kind of implementations are pretty big to carry, and its not worth imho.
