### ISSUE TITLE
Emit event on overflow

### ISSUE THREAD

**Issue by chenlevy** [Frondor/vue-line-clamp#19]
Thanks for the library!
I want to add read more button behavior that will only be shown if the overflow occurred.
in order to do that i need some simple indication that the paragraph is collapsed.

**Comment by Frondor** [comment]
Hello! Since the directive doesn't keep any state, and we can't get any info whenever the truncation happens, not without doing some dirty hacks on style-checks, you can only rely on the `lines` parameter you've passed to the directive value. Set it to `0` to activate the "read more" (hence discovering the full text), and hide the button, and/or toggle it to put back the default value.

**Comment by chenlevy** [comment]
Thanks for the fast reply!

I followed your suggestion but still I don't have any good indication
whether to show the "read more" button. I guess the best thing I can do
would be to use one of the style hacks you just mentioned.

Thanks again!

**Comment by Frondor** [comment]
I encourage you not to do that :smile:  That's going to be a bit overkill, and in my opinion, you should re-consider the implementation you have in mind, maybe go for another UX solution. Personally, I don't know any live website that detects whether the text is being truncated by css or not.

**Comment by chenlevy** [comment]
What do you think about this solution, is it overkill in your opinion?
`isEllipsActive (index) {`
`      if (this.$refs.content && this.$refs.content[index]) {`
`        var e = this.$refs.content[index]`
`        return (e.offsetHeight < e.scrollHeight)`
`      }`
`      return false`
`    }`

**Comment by Frondor** [comment]
Is that a computed property? References are not reactive, I'm not really sure that would work tbh.
