### ISSUE TITLE
Line-height overwritten in Firefox 64.0.2

### ISSUE THREAD

**Issue by bluetomato** [Frondor/vue-line-clamp#24]
The line-height set by class gets overwritten by vue-line-clamp element style line-height (16px) in Firefox 64.0.2. Try your own codepen in Firefox: https://codepen.io/Frondor/pen/ypvPEQ.

Yes, I'm aware that i can use '!important' for this issue, but I'd rather not do that.

P.S.: thanks for this plugin! Good work!

**Comment by Frondor** [comment]
Hello Steph, it's a common limitation we face in order to enforce consistence between browsers, when the fallback method is activated.
You need to provide a`line-height` argument if the browser doesn't support the webkit property.
That's why you can pass an argument to the directive in order to inline the `line-height` style, for instance: `v-line-clamp:20="lines"` (equals `line-height: 20px`)
Unless you got a solution for this?

**Comment by bluetomato** [comment]
Hey Frederico, thanks for your quick reply! Gotcha, I totally missed that... my bad. It works well, if i provide the line-height argument as you said. 

I don't have a proper solution for this, but I'll come back if I have one!
