### ISSUE TITLE
allow customization of fallback behavior

### ISSUE THREAD

**Issue by zevdg** [Frondor/vue-line-clamp#6]
So I wasn't totally happy with the default fallback behavior of this library.  Specifically, I wanted ellipsis.  I went ahead and made a local fork that simply replaced these lines https://github.com/Frondor/vue-line-clamp/blob/4dc34e0f0d1f3581ee1ccd6fcfc0870a427ed426/src/main.js#L14-L24 
with 
```javascript
lineClamp(el, { lineCount: lines });
```
from https://www.npmjs.com/package/line-clamp

This seemed like too disruptive of a change to push upstream.  There are [several different ways](https://css-tricks.com/line-clampin/) to do do line clamping on non-webkit browsers even without considering [word splitting issues](https://github.com/bsidelinger912/shiitake#shiitake).  Different projects may have different requirements and I don't want to force my preferences on everyone.

However, if we added a new "fallbackFunc" option, then we can let users override the default behavior with one of their own construction.  I went ahead and [modified my fork](https://github.com/zevdg/vue-line-clamp/compare/multi-element...zevdg:fallbackFunc) to do this.

Now, I can initialize this library like so

```javascript
import Vue from 'vue'
import VueLineClamp from 'vue-line-clamp'
import lineClamp from 'line-clamp'

Vue.use(VueLineClamp, {
  fallbackFunc: (el, bindings, lines) => {
    lineClamp(el, { lineCount: lines })
  }
})
```

and get the behavior I'm looking for.

If you like the idea, I can submit my fork as a PR.

**Comment by Frondor** [comment]
Sure!
I agree actual fallback method being quite weak, or too simple. But that's what I wanted, something really lightweight and mostly handled by CSS. Which comes with the trade-off of ellipsis of course.

**Comment by zevdg** [comment]
submitted.  My itches are all scratched now, but if you want to keep the default pure CSS, you still might want to consider adding a fade out effect like https://codepen.io/nilsynils/pen/KgaRBo?editors=1100

that's the best looking pure CSS solution i've seen.

**Comment by Frondor** [comment]
Thank you!
The reason why I didn't adopted the gradient / fake ellipsis fallback is because the appended pseudo element needs to be aware of its container background color (see https://codepen.io/Frondor/pen/LQLVPQ).
That can be easily handled by javascript, but I'm not really sure how "lightweight" is that in some cases where tons of truncated texts are being rendered (like a big news feed with "infinite scrolling").

This is one of the reasons I'm not using `getComputedStyle` for calculating automatically the `line-height`. See https://gist.github.com/paulirish/5d52fb081b3570c81e3a#getcomputedstyle

I'll check your submissions in a moment

**Comment by zevdg** [comment]
ah, makes sense
