### ISSUE TITLE
enhancement suggestion: do not modify div on certain inputs (probably undefined and null)

### ISSUE THREAD

**Issue by zevdg** [Frondor/vue-line-clamp#8]
I've worked around this in my code-base, but i was slightly surprised by one last behavior of this lib.  I had a div that needed to be clamped in some cases and not clamped in others.  I expected that if I passed 0 (or at least null or undefined), that this lib would leave my div unchanged.  However, to my surprise, there was no way to prevent this lib from modifying the element.  AFAIK, vue doesn't have a way to conditionally add an attribute to an element in a template, so i had to conditionally render 2 different versions of the div.  one with this attribute and one without.

TBH,  there are tradeoffs either way and i'm not convinced that this suggestion is a good one, but i figured i'd let you know about the pain point.

**Comment by Frondor** [comment]
I don't know if I get your point, although its a good one.
We agree that a falsy value should not truncate the text at all (which is actual behavior). But there is a need for the directive to actually modify the element in order to remove any (since its value is reactive) previous truncation.
I don't know what kind of "modification" you're talking about, you mean the class addition?

At the moment, the directive binds the styles at `bind` hook (which happens once at rendering), so we avoid the overhead of doing that on every `truncateText()` call.

**Comment by zevdg** [comment]
I'll put together an example to illustrate what i'm trying to say.

**Comment by zevdg** [comment]
Ok, so this is was basically my pain point and how i worked around it.  In short, i wanted my display property to not get clobbered in the cases where i didn't need the line clamping.

https://codepen.io/zevdg/pen/gvRpmN

Hypothetically, this lib could be changed to not clobber ANY css properties until a non-null/undefined value was passed to the attribute.  However, this "fix" could cause confusion for users that reactively toggle the property between a number and null.  An initial value of null would have the very different CSS than the same component after it was toggled to a valid number and then back to null.

**Comment by Frondor** [comment]
Sorry for the late response, I forgot to reply the notification.

What you want is quite difficult to achieve indeed. I've made an attempt but to be honest, it doesn't really feel polished enough to me.
This comes with the cost of removing the user warning for `NaN` values, since said value has been used to prevent the initial styling of the element (a valid integer can be set "reactively" so the element becomes properly stylized). 

PR: https://github.com/Frondor/vue-line-clamp/pull/9
Demo: https://codepen.io/Frondor/pen/yvvmBO

**Comment by zevdg** [comment]
yeah, i'm with you.  the workaround isn't that bad and the solutions introduce weird complexity.  Thanks for trying!
